Session/8
mqkotoo/flutter_training pull request #21
Opened 2023-09-15 10:03 UTC by mqkotoo

## 課題

close #9 

## 対応箇所

- [ ] xxx

## 動作

| expected | actual |
|----------|--------|
| xxx      | xxx    |

2023-09-18 09:29 UTC, mqkotoo reviewed
初めてARCHITECTURE.mdを書いて要領があんまりわかってない可能性があるので、アドバイスやフィードバックあればお願い致します。

2023-09-18 09:29 UTC, mqkotoo commented on lib/state/weather_state.dart
> +  }
`weatherState`の操作を行う関数
天気の取得に成功したら、データを保持して、失敗のケースは引数に`onError`を受け取ってView側でエラーのダイアログを表示する

2023-09-18 09:29 UTC, mqkotoo commented on analysis_options.yaml
> +    - custom_lint
riverpod_lintを有効にする

2023-09-19 09:35 UTC, trm11tkr requested changes
一旦いくつかコメントさせていただきました！
続きは明日見させていただきます！

2023-09-19 09:35 UTC, trm11tkr commented on analysis_options.yaml
> +    always_use_package_imports: true
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg) 
元々このルールは適用されていそうですが、あえて指定した意図は何かございますか？

https://github.com/blendthink/flutter-mobile-lints/blob/c4660454d27549da90bc318db72d14fb842df965/lib/recommended.yaml#L14C33-L14C33

2023-09-19 09:35 UTC, trm11tkr commented on doc/ARCHITECTURE.md
> +* Sateレイヤでなんらかの状態を操作して保管する。
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
```suggestion
* Stateレイヤでなんらかの状態を操作して保管する。
```

2023-09-19 09:35 UTC, trm11tkr commented on lib/utils/provider/yumemi_weather_client.dart
> +}
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
アロー演算子で書くと「初回はエラーをスローする」ことがさらに明確になり、可読性が向上するかもしれません
```suggestion
@riverpod
YumemiWeather yumemiWeatherClient(YumemiWeatherClientRef ref) =>
  throw UnimplementedError();
```

2023-09-19 09:35 UTC, trm11tkr commented on lib/utils/provider/yumemi_weather_client.dart
> +//初回に上書きしてキャッシュして使うので、直接アクセスはできないようにする
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
上書きすることで今回の場合どのようなメリットを想定されているのでしょうか？
少しピンときていないので教えていただきたいです！

2023-09-19 09:35 UTC, trm11tkr commented on lib/service/weather_service.dart
> +  return WeatherService(ref.read(yumemiWeatherClientProvider));
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
Provider の build 内なので `watch`の方が適切そうです！
[公式ドキュメント](https://docs-v2.riverpod.dev/docs/concepts/reading#obtaining-a-ref-object:~:text=ref.watch%20is%20used%20inside%20the%20build%20method%20of%20a%20widget%20or%20inside%20the%20body%20of%20a%20provider%20to%20have%20the%20widget/provider%20listen%20to%20a%20provider%3A)

2023-09-19 09:35 UTC, trm11tkr commented on doc/image/architecture.jpg
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
現在記載してくださっているのはアーキテクチャではなく、 Provider の依存関係図ですね…！

あと、記述方法をお伝えし忘れていました🙏
手書きだと内容に変更があった際に、修正が難しいため [mermaid記法](https://notepm.jp/help/mermaid)等で記述するのがおすすめです！
また、Provider の依存関係図は[riverpod_graph](https://github.com/rrousselGit/riverpod/tree/master/packages/riverpod_graph) を使うと自動生成できるのでおすすめです！

2023-09-20 01:53 UTC, mqkotoo commented on analysis_options.yaml
> +    always_use_package_imports: true
そうなんですね、僕のIDEでは警告が出てくれなかったので、追加しちゃいました。
様子みてみます。

2023-09-20 02:50 UTC, mqkotoo commented on lib/utils/provider/yumemi_weather_client.dart
> +//初回に上書きしてキャッシュして使うので、直接アクセスはできないようにする
Riverpod公式では、あるオブジェクトを差し替えたり、モッキングする際は、プロバイダーをオーバーライドする方法が紹介されているので、そちらを採用しています。
Ref: https://docs-v2.riverpod.dev/docs/cookbooks/testing#overriding-the-behavior-of-a-provider-during-tests

`throw UnimplementedError()`ではなくて、あらかじめ`YumemiWeather()`を入れておいて、テストの場合はモックのクライアントで上書きしてもいいんじゃないか。という質問でしょうか。

→普段`SharedPreferences`のインスタンス化をする際にこの方法を使っていて（インスタンス化は非同期なので、アプリを立ち上げるタイミングでインスタンス化してキャッシュしておく）その癖で書いてしまったのですが、mainで`override`して使うルールにすると少し安全に開発できるかなと考えたのですが、今考えるとそこまでメリットはないかもしれないですね。。。

2023-09-20 06:46 UTC, trm11tkr commented on README.md
> +* freezed等のコード生成
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
自動生成ファイルを `gitignore`に指定していないためこちらは不要だと思われます！

2023-09-20 06:46 UTC, trm11tkr commented on lib/utils/provider/yumemi_weather_client.dart
> +//初回に上書きしてキャッシュして使うので、直接アクセスはできないようにする
> throw UnimplementedError()ではなくて、あらかじめYumemiWeather()を入れておいて、テストの場合はモックのクライアントで上書きしてもいいんじゃないか。という質問でしょうか。

はい！こちらの意図でした🙇

![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
> 普段SharedPreferencesのインスタンス化をする際にこの方法を使っていて（インスタンス化は非同期なので、アプリを立ち上げるタイミングでインスタンス化してキャッシュしておく）その癖で書いてしまったのですが、

おっしゃる通り、インスタンスの生成が非同期の場合はこのアプローチがベストプラクティスかと思われますが、今回の場合はProvider 内で生成してあげる方が自然かもしれません。

![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
> mainでoverrideして使うルールにすると少し安全に開発できるかなと考えたのですが

こちらの安全の意図が把握できていないので教えていただきたいです 👀

2023-09-20 06:46 UTC, trm11tkr commented on doc/image/architecture.jpg
> 現在記載してくださっているのはアーキテクチャではなく、 Provider の依存関係図ですね…！

`architecture.jpg` -> `provider_dependencies.jpg` のような命名が適切そうでした…！（ただ、mermaid に書き直していただこうと思うのでこちらは削除されますかね…!）

2023-09-20 07:19 UTC, mqkotoo commented on README.md
> +* freezed等のコード生成
すみませんミスです！
ありがとうございます！

2023-09-20 07:24 UTC, mqkotoo commented on lib/utils/provider/yumemi_weather_client.dart
> +//初回に上書きしてキャッシュして使うので、直接アクセスはできないようにする
と、なんとなく考えていたのですが、今回の場合特にメリットないですね。。というコメントでした！笑

2023-09-20 07:53 UTC, mqkotoo commented on analysis_options.yaml
> +    always_use_package_imports: true
エディタの再起動で適応されました。済

2023-09-20 08:57 UTC, mqkotoo commented on lib/service/weather_service.dart
> +  return WeatherService(ref.read(yumemiWeatherClientProvider));
済

2023-09-20 10:22 UTC, mqkotoo commented on README.md
> +* freezed等のコード生成
済

2023-09-21 01:42 UTC, trm11tkr commented on doc/ARCHITECTURE.md
> +## アーキテクチャ
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
アーキテクチャいい感じで設計できていますね😍

ただ、State, Service, View, Model 等がどういう責務を持っているかを記載できればさらに良くなりそうです！（※ 現在は各 Widget の説明ベースになっているような気がします…！）

ここら辺いったんハドルにてお話しさせていただきたいです！！

2023-09-21 01:42 UTC, trm11tkr commented on lib/state/weather_state.dart
> +class WeatherState extends _$WeatherState {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
`WeatherState`だと、state が 天気を操作する処理を保持しているように見えて若干違和感がありそうです。
↓のように Notifier の サフィックスを加えてあげると誤解を招く恐れはなくなるかと思いました！
```suggestion
class WeatherStateNotifier extends _$WeatherStateNotifier {
```

2023-09-22 09:51 UTC, mqkotoo commented on lib/state/weather_state.dart
> +class WeatherState extends _$WeatherState {
フィードバックありがとうございます❤️
こちらで対応しました -> b91f7cea7bcd913b5f7cd4cf4a6851e059c3ba24

こちら一つ質問があります。
ファイル名はそのままでも良さそうではありますが、感覚とこれまでの経験のイメージですがクラス名とファイル名は同じことが多いため名前とクラス名を違った命名にするのは、少し複雑性、誤読等を招くとも思いました。（一緒の命名にした方がいいと言うようなドキュメントは見つけられませんでした）
こちらどう思いますでしょうか。

ファイル名も`Notifier`がつくとしたら、`View`層の中で`Notifier`というディレクトリを作って配置しているプロジェクトを見かけることがあるのですが、ディレクトリ構造についても意見があれば教えていただきたいですし、今度相談お願いします🙇

2023-09-22 09:51 UTC, mqkotoo commented on doc/ARCHITECTURE.md
> +## アーキテクチャ
更新してみました -> 2a40bf001e415440731b7f38a75d6b9b99a89d9c

2023-09-22 09:56 UTC, mqkotoo commented on lib/model/weather_forecast.dart
> +  const factory WeatherForecast({
フィードバックいただいたように、`WeatherData`という抽象的な命名を`WeatherForecast`に変更しました。
→ f349515b52bb4465555da9b904965f6c214d24f0

こちらの変更で、天気の情報を表示していたコンポネント、`WeatherForecast`ウィジェットと命名が重複してしまうので、ウィジェット側を`WeatherForecast` → `WeatherForecastPanel`という命名に変更しました。
→ 40bd88fa926ed0b0e2ee07b1bfe2f6d667bc4fe8

2023-09-26 09:33 UTC, trm11tkr requested changes
いくつかコメントさせていただきました！
実装自体は問題なさそうです！

2023-09-26 09:33 UTC, trm11tkr commented on doc/ARCHITECTURE.md
> +* `weatherStateProvider`で天気取得に失敗した場合は、エラーメッセージを表示する。
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
こちら更新お願いします…！
```suggestion
* `Reload`ボタンを押して、`weatherStateNotifierProvider`をreadして、天気の取得処理を行う。
* `weatherStateNotifierProvider`で天気取得に失敗した場合は、エラーメッセージを表示する。
```

2023-09-26 09:33 UTC, trm11tkr commented on lib/model/weather_forecast.dart
> +class WeatherForecast with _$WeatherForecast {
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
より正確に命名されたことで認識齟齬の危険性も下がりましたね😍

2023-09-26 09:33 UTC, trm11tkr commented on analysis_options.yaml
> +    duplicate_ignore: ignore
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey) 
https://github.com/rrousselGit/riverpod/commit/eb66dd199d7ae97d16c13660b3066b121aa475a3

2023-09-26 09:33 UTC, trm11tkr commented on lib/view/weather_view/component/weather_forecast_panel.dart
> +    final weatherData = ref.watch(weatherStateNotifierProvider);
![nits-badge](https://img.shields.io/badge/review-nits-green.svg) 
ここも `state` や `weatherState` に統一してしまってもいいかもですね…！

2023-09-26 09:33 UTC, trm11tkr commented on doc/graph.md
> +```mermaid
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
こちらも 更新お願いします！
今後の Session に関してもですが、コードを修正した場合は、
アーキテクチャ・依存関係のグラフを都度反映させるように意識すると良さそうです…！

2023-09-26 09:33 UTC, trm11tkr commented on doc/ARCHITECTURE.md
> +```mermaid
[graph.md](https://github.com/mqkotoo/flutter_training/blob/4391026b851549be65e6f82f8893e7017c7ca4b2/doc/graph.md) で記載いただいているので`ARCHITECTURE.md`内ではこちら不要そうですね…！
おそらく自分が間違って提案してしまいました🙇

2023-09-26 13:44 UTC, mqkotoo commented on doc/ARCHITECTURE.md
> +```mermaid
graph.mdはARCHITECTURE.mdに挿入しなくても良いということでしょうか。

2023-09-26 14:00 UTC, mqkotoo commented on lib/view/weather_view/component/weather_forecast_panel.dart
> +    final weatherData = ref.watch(weatherStateNotifierProvider);
フィードバックありがとうございます。
こちらで対応しました　→ 1f88e72cf20d861b16c35ac3a01669c4ff351e33

2023-09-27 01:37 UTC, trm11tkr commented on doc/ARCHITECTURE.md
> +```mermaid
@mqkotoo 
こちら逆でした🙏
`graph.md`は削除してしまって、`ARCHITECTURE.md`に記載するだけで良さそうかなと思いました！

2023-09-27 01:40 UTC, mqkotoo commented on doc/ARCHITECTURE.md
> +```mermaid
理解しました！
今の状態からgraph.mdだけ削除する形に変更します！

2023-09-27 01:50 UTC, mqkotoo commented on doc/ARCHITECTURE.md
> +```mermaid
@trm11tkr 
すみません、一点だけ。何度もすみません🙏
riverpodの依存関係が変わると、graph.mdを自動生成しなおす形で修正するので、graph.mdは取っておいても良いと思ったのですが、どうでしょうか。

→自己解決しました。
`dart pub global run riverpod_graph:riverpod_graph | pbcopy`
このようにコピーして使えば良さそうですね。

2023-09-27 01:59 UTC, mqkotoo commented on doc/ARCHITECTURE.md
> +```mermaid
こちらで削除しました。 [Delete graph.md](https://github.com/mqkotoo/flutter_training/pull/21/commits/2de8a51b3b10ef0a10271d4d79e8fb5a1cb471c7)

2023-09-27 04:29 UTC, mqkotoo commented on doc/ARCHITECTURE.md
> +* `weatherStateProvider`で天気取得に失敗した場合は、エラーメッセージを表示する。
こちらで対応 -> [Update ARCHITECTURE.md](https://github.com/mqkotoo/flutter_training/pull/21/commits/d297f58e13df39248ee59da5d68e4eda0468dca8)

2023-09-27 09:10 UTC, trm11tkr requested changes
最後に一点だけ修正漏れの対応お願いします…！

2023-09-27 09:10 UTC, trm11tkr commented on doc/ARCHITECTURE.md
> +  weatherStateProvider[["weatherStateProvider"]];
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
ここも `weatherStateNotifierProvider`ですかね🙏

2023-09-27 09:13 UTC, mqkotoo commented on doc/ARCHITECTURE.md
> +  weatherStateProvider[["weatherStateProvider"]];
何度もすみません、すでに消したgraph.mdの内容を更新して、更新したと勘違いしておりました🙏

2023-09-27 09:14 UTC, mqkotoo commented on doc/ARCHITECTURE.md
> +  weatherStateProvider[["weatherStateProvider"]];
こちらで対応しました! 177b379344621054af18607bf0863db8779f3c74

2023-09-27 09:33 UTC, trm11tkr approved these changes
本当にお疲れ様でした！
アーキテクチャを意識した綺麗なコードへの置き換えによって、拡張性・保守性が高くなりましたね ✨
![LGTM](https://image.lgtmoon.dev/119833)

2023-09-27 09:48 UTC, merged